config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'topics#index'
  resources :topics do
    resources :posts do
      resources :ratings, only: [:create]
      resources :comments, only: [:create, :destroy] do
        resources :user_comment_ratings, only: [:index, :create]
      end
    end
  end

  resources :tags
  get '/posts', to: 'posts#index'
  post '/topics/:topic_id/posts/:id/user_status', to: 'posts#user_status'
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3 }
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[show edit update destroy]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show; end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit; end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic
        if @topic.update(topic_params)
          format.html { redirect_to topic_url(@topic), notice: 'Topic was successfully updated.' }
          format.json { render :show, status: :ok, location: @topic }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @topic.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to topics_url, notice: 'Topic is not found' }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    if @topic
      @topic.destroy
      respond_to do |format|
        format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to topics_url, notice: 'Topic is not found'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find_by(id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <div class="d-flex justify-content-center">
    <div class="card w-25 p-4 mt-5 mb-3">
      <div class="field">
        <%= form.label :title, "Enter the Title :", class: "form-label fs-6 fw-bold" %>
        <%= form.text_field :title, class: "form-control" %>
        <% if topic.errors.any? %>
          <% if topic.title.length < 3 %>
            <span class="text-danger mt-1"><%= topic.errors.full_messages.first %></span>
          <% end %>
        <% end %>
      </div>
      <div class="actions text-center m-0 mt-2">
        <%= form.submit class: 'btn btn-primary btn-sm' %>
      </div>
    </div>
  </div>
<% end %>

app/views/topics/edit.html.erb
<% if @topic %>
  <h1 class="text-center h2 my-3">Editing Topic</h1>
  <%= render 'form', topic: @topic %>
  <div class="text-center">
    <%= link_to '< Back', topics_path, class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
    <%= link_to 'Show', topic_posts_path(@topic), class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
  </div>
<% else %>
  <p class="text-center fw-bold text-danger">🙁 Topic doesn't exist</p>
  <div class="text-center mt-4">
    <%= link_to '< Back', topics_url, class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
  </div>
<% end %>

app/views/topics/index.html.erb
<% if flash[:warning] != nil %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <p id="notice text-danger" class="m-0"><%= flash[:warning] %></p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if notice != nil %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <p id="notice text-success" class="m-0"><%= notice %></p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert != nil %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <p id="notice text-warning" class="m-0"><%= alert %></p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<h1 class="text-center h2 my-3">Topics</h1>
<% @topics.each do |topic| %>
  <div class="alert alert-secondary bg-white d-flex shadow-sm">
    <h4 class="flex-grow-1 my-0"><%= topic.title %></h4>
    <div class="">
      <%= link_to 'Show', topic_posts_path(topic), class: "btn btn-sm btn-primary text-light me-2" %>
      <%= link_to 'Edit', edit_topic_path(topic), class: "btn btn-sm btn-success text-light me-2" %>
      <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger text-light" %>
    </div>
  </div>
<% end %>

app/views/topics/new.html.erb
<h1 class="text-center h2 my-3">New Topic</h1>

<%= render 'form', topic: @topic %>

<div class="text-center">
  <%= link_to '< Back', topics_path, class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
</div>

app/views/topics/show.html.erb
<% if notice != nil %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <p id="notice" class="m-0"><%= notice %></p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if @topic %>
<div class="d-flex justify-content-center align-items-center">
  <div class="card w-50 mt-5 mb-3 p-3">
    <h3 class="text-center card-subtitle text-secondary">Topic : <i><%= @topic.title %></i></h3>
  </div>
</div>

<div class="text-center">
  <%= link_to '< Back', topics_path, class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
  <%= link_to 'Edit', edit_topic_path(@topic), class: "btn btn-sm btn-primary text-light me-2 fw-bold border-primary border-2" %>
  <%= link_to 'Posts',topic_posts_path(@topic), class: "btn btn-sm btn-primary text-light me-2 fw-bold border-primary border-2" %>
</div>
<% else %>
  <p class="text-center fw-bold text-danger">🙁 Topic doesn't exist</p>
  <div class="text-center mt-4">
    <%= link_to '< Back', topics_url, class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
  </div>
<% end %>