config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'topics#index'
  resources :topics do
    resources :posts do
      resources :ratings, only: [:create]
      resources :comments, only: [:create, :destroy] do
        resources :user_comment_ratings, only: [:index, :create]
      end
    end
  end

  resources :tags
  get '/posts', to: 'posts#index'
  post '/topics/:topic_id/posts/:id/user_status', to: 'posts#user_status'
end

app/models/user_comment_rating.rb
class UserCommentRating < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  validates :point, presence: true
  validates :point, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/controllers/user_comment_ratings_controller.rb
class UserCommentRatingsController < ApplicationController
  before_action :set_topic
  before_action :set_post
  before_action :set_comment

  def index
    @ratings = @comment.user_comment_ratings.includes(:user)
  end

  def create
    @rating = @comment.user_comment_ratings.new(rating_params.merge(user_id: current_user.id))
    if @rating.save
      redirect_to topic_post_path(@post.topic, @post)
    else
      redirect_to topic_post_path(@post.topic, @post), info: @rating.errors.full_messages.first
    end
  end

  private

  def set_topic
    @topic = Topic.find_by(id: params[:topic_id])
  end

  def set_post
    @post = @topic.posts.find_by(id: params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find_by(id: params[:comment_id])
  end

  def rating_params
    params.require(:user_comment_rating).permit(:point)
  end
end

app/views/user_comment_ratings/_form_comment_rating.html.erb
<% unless comment.user_comment_ratings.where(user_id: current_user.id).exists? %>
  <div class="alert alert-secondary bg-white mt-2">
    <%= form_with model: [@topic, @post, comment, comment.user_comment_ratings.new], url: "/topics/#{@topic.id}/posts/#{@post.id}/comments/#{comment.id}/user_comment_ratings" do |form| %>
      <div class="mb-0 d-flex">
      <span class="d-flex me-2">
        <%= form.radio_button :point, 1, class: "me-1 form-check-input" %>
        <%= form.label :point_1, "1 Star", class: "form-check-label" %>
      </span>
        <span class="d-flex me-2">
        <%= form.radio_button :point, 2, class: "me-1 form-check-input" %>
          <%= form.label :point_2, "2 Star", class: "form-check-label" %>
      </span>
        <span class="d-flex me-2">
        <%= form.radio_button :point, 3, class: "me-1 form-check-input" %>
          <%= form.label :point_3, "3 Star", class: "form-check-label" %>
      </span>
        <span class="d-flex me-2">
        <%= form.radio_button :point, 4, class: "me-1 form-check-input" %>
          <%= form.label :point_4, "4 Star", class: "form-check-label" %>
      </span>
        <span class="d-flex me-2">
        <%= form.radio_button :point, 5, class: "me-1 form-check-input" %>
          <%= form.label :point_5, "5 Star", class: "form-check-label" %>
      </span>
      </div>
      <p class="mt-0 text-danger"><%= flash[:info] %></p>
      <div class="mt-3">
        <%= form.submit 'Give a Rating', class: "btn btn-outline-dark btn-sm" %>
      </div>
    <% end %>
  </div>
<% else %>
  <%= link_to 'Ratings List', topic_post_comment_user_comment_ratings_path(@topic, @post, comment), class: 'text-secondary bg-white fw-bold border-2 mt-3 d-block' %>
<% end %>

app/views/user_comment_ratings/index.html.erb
<h3 class="mt-3 text-center">Ratings for Comment : <%= @comment.body %></h3>
<p class="mt-2 text-center">By : <%= @comment.user.email %></p>
<section class="container d-flex justify-content-center">
  <table class="table w-50 mt-3 text-center">
    <thead>
    <tr>
      <th scope="col">Rating</th>
      <th scope="col">User</th>
    </tr>
    </thead>
    <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.point %></td>
        <td><%= rating.user.email %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>
<div class="text-center">
  <%= link_to '< Back', topic_post_path(@topic, @post), class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
</div>

