config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'topics#index'
  resources :topics do
    resources :posts do
      resources :ratings, only: [:create]
      resources :comments, only: [:create, :destroy] do
        resources :user_comment_ratings, only: [:index, :create]
      end
    end
  end

  resources :tags
  get '/posts', to: 'posts#index'
  post '/topics/:topic_id/posts/:id/user_status', to: 'posts#user_status'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_and_belongs_to_many :users
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_and_belongs_to_many :tags
  has_one_attached :image
  validates_associated :tags
  accepts_nested_attributes_for :tags
  validates :title, presence: true, length: { minimum: 3, maximum: 20 }
  validates :body, presence: true, length: { minimum: 3 }
  validate :acceptable_image

  scope :filter_date, ->(fromDate, toDate) { where('created_at >= ? AND created_at <= ?',fromDate,toDate.end_of_day) }

  def acceptable_image
    return unless image.attached?

    unless image.byte_size <= 1.megabyte
      errors.add(:image, 'size is too big,should be less than 1 MB')
    end

    acceptable_types = ['image/jpeg', 'image/png']
    unless acceptable_types.include?(image.content_type)
      errors.add(:image, 'must be png or jpeg')
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_topic
  skip_before_action :verify_authenticity_token, only: [:user_status]
  before_action :get_post, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /topics/:topic_id/posts
  def index
    if params[:fromDate].present? && params[:toDate].present?
      @pagy, @posts = @topic ? pagy(@topic.posts, items: 10) : pagy(Post.includes(:topic).filter_date(params[:fromDate], params[:toDate].to_date), items: 10)
      @read_posts = current_user.read_posts.to_a
    else
      @pagy, @posts = @topic ? pagy(@topic.posts, items: 10) : pagy(Post.includes(:topic).filter_date(Date.yesterday, Date.today), items: 10)
      @read_posts = current_user.read_posts.to_a
    end
  end

  # GET /topics/:topic_id/posts/:id
  def show
      @comments = @post.comments.includes(:user)
      @post_tags = @post.tags
      @ratings = @post.ratings.group(:point).order(:point).count
  end

  # GET /topics/:topic_id/posts/new
  def new
    @post = @topic ? @topic.posts.new : nil
  end

  # GET /topics/:topic_id/post/:id/edit
  def edit; end

  # POST /topics/:topic_id/posts
  def create
    @post = @topic.posts.new(post_params.merge(user_id: current_user.id))
    @post.tags_attributes = get_tags if get_tags
    respond_to do |format|
      if @post.save
        format.html { redirect_to topic_post_path(@topic, @post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js { render :create, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/:topic_id/posts/:id
  def update
    respond_to do |format|
      if @post
        if @post.update(post_params)
          format.html { redirect_to topic_post_path(@topic, @post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to topic_posts_path(@topic), notice: 'Post not found' }
      end
    end
  end

  def destroy
    if @post
      @post.destroy
      respond_to do |format|
        format.html { redirect_to topic_posts_path(@topic), notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to topic_posts_url(@topic), notice: 'Post not found'
    end
  end

  def user_status
    @post = @topic.posts.find(params[:id])
    unless @post.users.where(email: current_user.email).exists?
      @post.users << current_user
    end
  end

  private

  def get_topic
    @topic = Topic.find_by(id: params[:topic_id])
  end

  def get_post
    @post = @topic.posts.find_by(id: params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :image, tag_ids: [])
  end

  def get_tags
    tags = []
    params[:post][:tags_attributes][:name].split(',').each do |p|
      tags.push({ name: p })
    end
    tags
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: [post.topic, post],id: 'new-form', local: false do |form| %>
  <div class="modal-body">
    <div class="field">
      <%= form.label :title, class: "form-label fs-6 fw-bold" %>
      <%= form.text_field :title, class: "form-control" %>
      <% if @post.errors.messages[:title].any? %>
        <span class="text-danger mt-1"><%= "Title #{@post.errors.messages[:title].first}" %></span>
      <% end %>
    </div>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
      <% if @post.errors.messages[:image].any? %>
        <span class="text-danger mt-1"><%= "File #{@post.errors.messages[:image].first}" %></span>
      <% end %>
    </div>
    <div class="field">
      <%= form.label :body, class: "form-label fs-6 fw-bold" %>
      <%= form.text_area :body, class: "form-control" %>
      <% if @post.errors.messages[:body].any? %>
        <span class="text-danger mt-1"><%= "Body #{@post.errors.messages[:body].first}" %></span>
      <% end %>
    </div>

    <div class="field">
      <p class="form-label fs-6 fw-bold">Add tags</p>
      <%= form.select :tag_ids, Tag.all.collect { |t| [t.name, t.id] }, { include_blank: false }, { multiple: true, class: "form-control" } %>
    </div>

    <div class="field">
      <p class="form-label fs-6 fw-bold">Create new tags</p>
      <%= form.fields_for :tags_attributes do |f| %>
        <%= f.text_field :name, class: 'form-control' %>
      <% end %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post_card.html.erb
<div class="alert alert-secondary bg-white shadow-sm me-2 width mb-2">
  <div class="position-relative">
    <h4><%= post.title %></h4>
    <% if post.users.where(email: current_user.email).exists? %>
      <small class="position-absolute positions badge rounded-pill bg-success">Read</small>
    <% else %>
      <small class="position-absolute positions badge rounded-pill bg-danger">Un Read</small>
    <% end %>
  </div>
  <h6 class="mb-3"><%= post.body[0..7] %> ...</h6>
  <p><%= post.comments_count %> Comments</p>
  <% if !@topic %>
    <small class="card-subtitle fw-bold d-block mb-2">Topic: <%= post.topic.title %></small>
  <% end %>
  <div>
    <% if can? :manage, post %>
      <%= link_to 'Edit Post', edit_topic_post_path(post.topic_id, post), class: "btn btn-sm btn-success text-light me-2" %>
      <%= link_to 'Delete Post', topic_post_path(post.topic, post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger text-light me-2" %>
    <% else %>
      <%= link_to 'Edit Post', edit_topic_post_path(post.topic_id, post), class: "btn btn-sm btn-success text-light me-2 disabled" %>
      <%= link_to 'Delete Post', topic_post_path(post.topic, post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger text-light me-2 disabled" %>
    <% end %>
  </div>
</div>

app/views/posts/create.js.erb
<% if response.status == 422 %>
  alert('<%= @post.errors.full_messages.first %>');
<% else %>
  document.getElementById('postsList').innerHTML += "<%= escape_javascript render('post_card', post: @post) %>";
  document.getElementById("loader").style.display = "block";
  setTimeout(() => {document.querySelector(".close-modal").click();},300);
  setTimeout(() => {alert('Post created successfully');},500);
<% end %>

app/views/posts/edit.html.erb
<% if @post %>
  <h2 class="text-center h2 my-3">Edit Post</h2>
  <%= render 'form', topic: @topic %>
  <div class="text-center">
    <%= link_to '< Back', topic_posts_path, class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
    <%= link_to 'Show', topic_post_path(@topic, @post), class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
  </div>
<% else %>
  <p class="text-center fw-bold text-danger">🙁 No Posts Found....</p>
  <div class="text-center mt-4">
    <%= link_to '< Back', topic_posts_url(@topic), class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<% if flash[:warning] != nil %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <p id="notice text-danger" class="m-0"><%= flash[:warning] %></p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if notice != nil %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <p id="notice text-success" class="m-0"><%= notice %></p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if !params[:topic_id] || @topic %>
<h1 class="text-center h2 my-3"><%= (@topic) ? @topic.title.capitalize : 'Posts' %></h1>
<% unless params[:topic_id].present? %>
  <section class="container mb-3">
    <form method="get" class="d-flex">
      <label for="fromDate">From:</label>
      <input type="date" id="fromDate" name="fromDate" value="<%= params[:fromDate].present? ? params[:fromDate] : nil %>">
      <label for="toDate" class="ms-3">To:</label>
      <input type="date" id="toDate" name="toDate" value="<%= params[:toDate].present? ? params[:toDate] : nil %>">
      <input type="submit" value="Show Details" class="ms-3">
    </form>
  </section>
<% end %>
<section class="w-100 d-flex flex-wrap" id='postsList'>
  <% if !@posts.empty? %>
    <% @posts.each do |post| %>
      <div class="alert alert-secondary bg-white shadow-sm me-2 width mb-2">
        <div class="position-relative">
          <h4><%= post.title %></h4>
            <% if @read_posts.index(post).present? %>
              <small class="position-absolute positions badge rounded-pill bg-success">Read</small>
            <% else %>
              <small class="position-absolute positions badge rounded-pill bg-danger">Un Read</small>
            <% end %>
        </div>
        <h6 class="mb-3"><%= post.body[0..7] %> ...</h6>
        <p><%= post.comments_count %> Comments</p>
        <p>Avg Rating : <%= post.rating_average %></p>
        <% if !@topic %>
          <small class="card-subtitle fw-bold d-block mb-2">Topic: <%= post.topic.title %></small>
        <% end %>
        <div>
          <%= link_to 'Show Post', topic_post_path(post.topic_id, post), class: "btn btn-sm btn-primary text-light me-2" %>
          <% if can? :manage, post %>
            <%= link_to 'Edit Post', edit_topic_post_path(post.topic_id, post), class: "btn btn-sm btn-success text-light me-2" %>
            <%= link_to 'Delete Post', topic_post_path(post.topic, post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger text-light me-2" %>
          <% else %>
            <%= link_to 'Edit Post', edit_topic_post_path(post.topic_id, post), class: "btn btn-sm btn-success text-light me-2 disabled" %>
            <%= link_to 'Delete Post', topic_post_path(post.topic, post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger text-light me-2 disabled" %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <section class="container text-center">
      <p class="fw-bold text-danger">🙁 No Posts Found....</p>
    </section>
  <% end %>
</section>
<section class="container d-flex justify-content-center mt-2">
  <%== pagy_bootstrap_nav(@pagy) %>
</section>
<div class="text-center mt-2">
  <%= link_to '< Back', topics_url, class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
  <% if (@topic) %>
    <%= link_to 'New Post', new_topic_post_path(@topic),data: {bs_toggle: 'modal', bs_target: '#newPostModal'}, remote: true, class: "btn btn-sm btn-primary text-light me-2 fw-bold border-primary border-2" %>
  <% end %>
</div>

  <div class="modal fade" id="newUserModal" tabindex="-1" aria-labelledby="newUserModalLabel" aria-hidden="true">
    <div id="loader" class="loader w-100 h-100 position-relative">
      <div class="spinner-grow text-info position-absolute top-50 start-50" role="status">
      </div>
    </div>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title fw-bold" id="newUserModalLabel">Create new post</h5>
          <button type="button" class="btn-close close-modal" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div id='newUserForm'>
        </div>
      </div>
    </div>
  </div>

<% else %>
  <p class="text-center fw-bold text-danger mt-3">🙁 Topic doesn't exist</p>
  <div class="text-center mt-4">
    <%= link_to '< Back', topics_url, class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
  </div>
<% end %>

<script>
    const element = document.getElementById("loader");
    element.style.display = "none";
</script>

app/views/posts/new.html.erb
<% render 'form', post: @post%>

app/views/posts/new.js.erb
document.getElementById('newPostForm').innerHTML = '<%= escape_javascript render('form', post: @post)%>'

app/views/posts/show.html.erb
<% if notice != nil %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <p id="notice" class="m-0"><%= notice %></p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if @post %>
<div class="d-flex justify-content-center align-items-center">
  <div class="container alert alert-secondary bg-white mt-5 mb-3 p-3">
    <% if @post.image.attached? %>
      <%= image_tag @post.image, style: "width: 100%; margin-bottom: 12px;" %>
    <% end %>
    <% if current_user.read_posts.index(@post).present? %>
      <small id='para' class="position-absolute positions badge rounded-pill bg-success mt-3 me-3">Read</small>
    <% else %>
      <small id='para' class="position-absolute positions badge rounded-pill bg-danger mt-3 me-3">Un Read</small>
    <% end %>
    <h3 class="text-capitalize fs-4 card-title fw-bold"><%= @post.title %></h3>
    <p class="fs-6 mt-2"><%= @post.body %></p>
    <% if @post_tags.present? %>
      <div class="mt-4">
        <span class="fs-6 fw-bold text-secondary fst-italic me-2">Tags:</span>
        <% @post_tags.each do |tag| %>
          <p class="fs-5 badge fs-6 bg-secondary rounded-pill mb-0 fw-normal"><%= tag.name %></p>
        <% end %>
      </div>
    <% end %>
    <h6 class="mt-3">Rating : <span class="badge bg-secondary rounded-pill"><%= @post.rating_average %></span></h6>
    <div class="d-flex mt-3">
      <% (1..5).each do |i| %>
        <h6><%= "#{i} Star" %> :
          <span class="me-3 badge bg-dark rounded-pill"><%= @ratings[i] ? @ratings[i] : 0 %></span></h6>
      <% end %>
    </div>
    <p class="mt-3 card-subtitle fw-bold ">by : <i><%= @post.user.email %></i></p>
    <p class="text-center mt-3 card-subtitle fw-bold ">Topic : <i><%= @post.topic.title %></i></p>
  </div>
</div>

<div class="text-center mb-3">
  <%= link_to '< Back', topic_posts_url, class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
  <% if can? :update, @post %>
    <%= link_to 'Edit post', edit_topic_post_path(@topic, @post), class: "btn btn-sm btn-primary text-light me-2 fw-bold border-primary border-2" %>
  <% else %>
    <%= link_to 'Edit post', edit_topic_post_path(@topic, @post), class: "btn btn-sm btn-primary text-light me-2 fw-bold border-primary border-2 disabled" %>
  <% end %>
</div>

<div class="container bg-white py-2 mt-3">
  <span>Give a rating :</span>
  <%= form_with model: [@topic, @post, @post.ratings.new], url: "/topics/#{@topic.id}/posts/#{@post.id}/ratings" do |form| %>
    <div class="mb-0 d-flex mt-3">
      <span class="d-flex me-2">
        <%= form.radio_button :point, 1, class: "me-1 form-check-input" %>
        <%= form.label :point_1, "1 Star", class: "form-check-label" %>
      </span>
      <span class="d-flex me-2">
        <%= form.radio_button :point, 2, class: "me-1 form-check-input" %>
        <%= form.label :point_2, "2 Star", class: "form-check-label" %>
      </span>
      <span class="d-flex me-2">
        <%= form.radio_button :point, 3, class: "me-1 form-check-input" %>
        <%= form.label :point_3, "3 Star", class: "form-check-label" %>
      </span>
      <span class="d-flex me-2">
        <%= form.radio_button :point, 4, class: "me-1 form-check-input" %>
        <%= form.label :point_4, "4 Star", class: "form-check-label" %>
      </span>
      <span class="d-flex me-2">
        <%= form.radio_button :point, 5, class: "me-1 form-check-input" %>
        <%= form.label :point_5, "5 Star", class: "form-check-label" %>
      </span>
    </div>
    <p class="mt-0 text-danger"><%= flash[:info] %></p>
    <div>
      <%= form.submit class: "btn btn-outline-dark btn-sm" %>
    </div>
  <% end %>
</div>

<div class="container bg-white py-2 mt-3">
  <h4>Comments | <%= @comments.length %></h4>
  <hr/>
  <% if @comments.present? %>
    <% @comments.each do |comment| %>
      <div class="alert alert-secondary bg-white d-flex py-2">
        <div class="flex-grow-1">
          <small class="fw-bold m-0"><%= comment.user.email %></small>
          <p class="fs-5 mt-3 mb-1"><%= comment.body %></p>
          <%= render "user_comment_ratings/form_comment_rating",comment: comment %>
        </div>
        <%= link_to 'X', "/topics/#{@topic.id}/posts/#{@post.id}/comments/#{comment.id}", method: :delete, data: { confirm: 'Are you sure?' }, class: "text-secondary bg-white text-decoration-none fs-5 mt-3" if can? :delete, comment %>
      </div>

    <% end %>
  <% else %>
    <div class="text-center">
      <p>No Comments</p>
    </div>
  <% end %>
</div>

<div class="container bg-white py-2 mt-3">
  <h4>Add a new comment:</h4>
  <%= form_with model: [@topic, @post, @post.comments.new], url: "/topics/#{@topic.id}/posts/#{@post.id}/comments" do |form| %>
    <div class="mb-0">
      <%= form.text_area :body, class: 'form-control mt-3', placeholder: "Type your views here..." %>
    </div>
    <p class="mt-0 text-danger"><%= flash[:error] %></p>
    <div>
      <%= form.submit class: "btn btn-outline-dark btn-sm" %>
    </div>
  <% end %>
</div>
<% else %>
  <p class="text-center fw-bold text-danger">🙁 No Posts Found....</p>
  <div class="text-center mt-4">
    <%= link_to '< Back', topic_posts_url(@topic), class: "btn btn-sm btn-outline-primary bg-light text-primary fw-bold border-2 me-2" %>
  </div>
<% end %>

<script>
    para = document.getElementById('para')
    if(para.textContent === 'Un Read') {
        fetch(`${location.pathname}/user_status`, {
            method: 'POST'
        })
            .then((res) => {
                if(res.ok) {
                    para.textContent = 'Read'
                    para.className = "position-absolute positions badge rounded-pill bg-success mt-3 me-3"
                }
            })
    }
</script>