config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'topics#index'
  resources :topics do
    resources :posts do
      resources :ratings, only: [:create]
      resources :comments, only: [:create, :destroy] do
        resources :user_comment_ratings, only: [:index, :create]
      end
    end
  end

  resources :tags
  get '/posts', to: 'posts#index'
  post '/topics/:topic_id/posts/:id/user_status', to: 'posts#user_status'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTrainingApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="bg-light">
<nav class="navbar py-3 navbar-expand-lg navbar-dark bg-dark">
  <div class="container-sm">
    <a class="navbar-brand" href="/">Blog App</a>
    <% if current_user %>
      <%= link_to "Edit Profile", edit_user_registration_path,data: {bs_toggle: 'modal', bs_target: '#newUserModal'}, remote: true, class: 'btn btn-light btn-sm active' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="w-100 d-flex flex-row-reverse navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sm active ms-2' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class: 'btn btn-info btn-sm active ms-2' %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'New Topic', new_topic_path, class: 'btn btn-light btn-sm active' %>
        </li>
        <li class="nav-item me-2">
          <%= link_to 'All Posts', posts_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item me-2">
          <%= link_to 'All Tags', tags_path, class: 'nav-link active' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<section class="container w-75">
  <%= yield %>
</section>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<div class="modal fade mh-100 overflow-hidden" id="newUserModal" tabindex="-1" aria-labelledby="newUserModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title fw-bold" id="newUserModalLabel">Edit User</h5>
        <button type="button" class="btn-close close-modal" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id='newUserForm'>
      </div>
    </div>
  </div>
</div>
</body>
</html>